apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: production
  app.kubernetes.io/managed-by: kustomize
namespace: prod

images:
- digest: sha256:a02690a2486468bcd72cbfeb2b9305e13970f9d3efa39742a2d42cfe8e850414
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: registry.gitlab.com/cloudnative_impress/bookinfo/reviews

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml
- serviceaccount.yaml
