apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-auth-secret
spec:
  backendType: gcpSecretsManager
  projectId: cloudnative-cicd-redhat
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: gitlab-auth
      name: .dockerconfigjson
