apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - list: 
      # Parameters are generated based on this cluster list, to be substituted
      # into the template below.
     elements:
     - cluster: stg
       url: https://kubernetes.default.svc
     - cluster: prod
       url: https://kubernetes.default.svc
  template: 
    # An Argo CD Application template, with support for parameter substitution 
    # with values from parameters generated above.
    metadata:
      name: reviews
    spec:
      project: '{{cluster}}-bookinfo'
      source:
        kustomize:
        repoURL: https://gitlab.com/cloudnative_impress/bookinfo-manifests.git
        targetRevision: main
        path: 'deploy/overlays/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
