apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: reviews-listener
spec:
  serviceAccountName: tekton-admin
  triggers:
  - name: push-events-topic-branches
    interceptors:
      - ref:
          name: "gitlab"
          kind: ClusterInterceptor
        params:
        - name: "secretRef"
          value:
            secretName: gitlab-webhook-token
            secretKey: secretToken
        - name: "eventTypes"
          value: ["Push Hook"]
    template:
      ref: build-deploy-bookinfo-template
    bindings:
      - ref: build-deploy-reviews-binding
