apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stg-bookinfo
  namespace: argocd
spec:
  description: BookInfo for Stating Environment
  destinations:
  - namespace: stg
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: tekton.dev
    kind: '*'
  - group: triggers.tekton.dev
    kind: '*'
  sourceRepos:
  - https://gitlab.com/___GITLAB_USER___/bookinfo-manifests.git
